export const SLIDES = [
    { src: "https://mir-s3-cdn-cf.behance.net/project_modules/max_3840/696eb631847075.56632d1c8ec85.jpg", alt: "", text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Reiciendis fugit facilis rem delectus ex corporis praesentium? Consectetur ratione sint quidem, fugiat voluptatem excepturi placeat error maiores debitis fugit laborum minus." },
    { src: "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/8e012431847075.56632d1c8da61.jpg", alt: "", text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Reiciendis fugit facilis rem delectus ex corporis praesentium? Consectetur ratione sint quidem, fugiat voluptatem excepturi placeat error maiores debitis fugit laborum minus." },
    { src: "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/40e2a731847075.56632d1c8ff04.jpg", alt: "", text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Reiciendis fugit facilis rem delectus ex corporis praesentium? Consectetur ratione sint quidem, fugiat voluptatem excepturi placeat error maiores debitis fugit laborum minus." },
    { src: "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/d033f931847075.56632d1c914ea.jpg", alt: "", text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Reiciendis fugit facilis rem delectus ex corporis praesentium? Consectetur ratione sint quidem, fugiat voluptatem excepturi placeat error maiores debitis fugit laborum minus." },
    { src: "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a5915031847075.56632d1c926bf.jpg", alt: "", text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Reiciendis fugit facilis rem delectus ex corporis praesentium? Consectetur ratione sint quidem, fugiat voluptatem excepturi placeat error maiores debitis fugit laborum minus. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Reiciendis fugit facilis rem delectus ex corporis praesentium? Consectetur ratione sint quidem, fugiat voluptatem excepturi placeat error maiores debitis fugit laborum minus." },
];

export const PROJECTS = [
    { title: 'Зимний дворец', imgUrl: 'https://static.tildacdn.com/tild3337-6633-4666-a566-613966323532/_1.jpeg', description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cumque iste at sit est sunt incidunt nostrum placeat in ex fuga amet odit minima itaque non facere nemo soluta explicabo unde iusto, aliquid dolores earum. Commodi natus cupiditate obcaecati reprehenderit ad soluta saepe illo atque. Beatae veritatis dolores fuga numquam rem.' },
    { title: 'Лахта центр', imgUrl: 'https://wlsn.ru/wp-content/uploads/2022/08/0-21.jpg', description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, aut inventore, eaque quod commodi voluptatem voluptate quo ut quae dignissimos a reprehenderit dolorem quaerat minima architecto libero hic deserunt eveniet cumque? Asperiores laborum fugiat natus qui sapiente magni, dolorum laudantium beatae esse inventore minus, fugit ipsum? Voluptate ex in natus enim dolorum nesciunt eaque distinctio maiores, eum ipsa deserunt dolore possimus voluptas fugit cupiditate voluptatem saepe quasi corporis consequuntur? Magnam unde accusantium fugiat quo fuga.' },
    { title: 'Крепость Орешек', imgUrl: 'https://static.tildacdn.com/stor3462-3863-4131-a635-633136636435/10286227.jpg', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio nostrum perspiciatis aperiam molestiae cupiditate, quisquam ut culpa provident iste vel reiciendis velit enim veniam facilis. Accusantium, est molestias ipsam, eos beatae libero numquam excepturi nostrum, illum atque ratione sapiente vitae? Quas aspernatur quaerat in praesentium, quam dignissimos ipsa culpa voluptatum aut perspiciatis eos vero provident ipsam officiis architecto distinctio repellat!' },
    { title: 'Пышечная', imgUrl: 'https://static.spaser.pw/petersburg/__what_and_where/other_eat/pyshechnaya/1.jpg', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos id, mollitia eius enim, nisi deleniti labore itaque excepturi repudiandae, magnam quaerat. Ipsam odio, similique nesciunt, minus fugiat veritatis expedita sequi facilis commodi minima quas sit consectetur porro consequuntur neque. Dolor deleniti perferendis saepe molestias cumque!' },
    { title: 'Рюмочная', imgUrl: 'https://i6.photo.2gis.com/images/branch/0/30258560091868932_7738.jpg', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate voluptatibus harum eveniet perferendis quo ad, recusandae vel molestiae. Aspernatur nulla nostrum iusto ea accusamus? Molestias sequi impedit dolorem qui cupiditate?' }
];